### ISSUE TITLE
how to do inference when data not posesses 'label' ?

### ISSUE THREAD

**Issue by zide05** [salesforce/factCC#1]
I want to predict the fact consistency of text and claim, what is the command to inference label of sample ?
Can the model print the level of consistency when getting one pair of text and claim ?

**Comment by 6desislava6** [comment]
I have the same question. Did you manage to answer it yourself? Thanks!

**Comment by kailashkarthik9** [comment]
I have the same question as well

**Comment by zhangzx-uiuc** [comment]
Same question here.

**Comment by AnujLahoty** [comment]
GUys and Girls, just poduce a fake (random) label entry in your data and obtain the predicrtions out of your model.
